# Generated by Django 4.2 on 2024-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/images/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
